### ISSUE TITLE
[Bug]: new content 404ing

### ISSUE THREAD

**Issue by mikemaccana** [ironforge-cloud/soldev-ui#16]
**Describe the bug:**
Hi Italo I'm not 100% sure if you're the right person for this, but there's some 404s of newer content on. Soldev - in particular, the 'Getting started' and 'Cryptography fundamentals' are 404ing. Not sure if you need to re-run some kind of process on the soldev.app site when we add new content.

**Steps to reproduce the behavior:**
1. Go to https://www.soldev.app/course
2. Click on [Getting started](https://www.soldev.app/course/getting-started)
4. See 404

I've let @jamesrp13 know too.

**Comment by jamesrp13** [comment]
Well shit guys, that sucks with us bringing so much attention to it yesterday with the announcement haha.

@italoacasas I thought this was automatic now. Any chance you can trigger a rebuild to see if that fixes it? We'll still need to make some change at some point but for now if that fixes it that'd be great.

**Comment by jamesrp13** [comment]
The rebuild fixed it for now. I want to look into a couple things to try and figure out what's happening
