### ISSUE TITLE
[Bug]: Recently added images are 404ing.

### ISSUE THREAD

**Issue by mikemaccana** [ironforge-cloud/soldev-ui#18]
**Describe the bug:**
Similar to https://github.com/ironforge-cloud/soldev-ui/issues/16, recently added images are 404ing.

Old image: https://www.soldev.app/assets/movie-reviews-frontend.png works
New image: https://www.soldev.app/assets/wallet-addresses.svg 404s

Both `img` elements use a relative path to `../assets` so I'm pretty sure both are correct/

Test URL: 

**Steps to reproduce the behavior:**
1. Go to https://www.soldev.app/course/intro-to-cryptography
2. Open the JS console
3. See error:
```
GET https://www.soldev.app/assets/wallet-addresses.svg 404 (Not Found)
```

**Expected behavior:**
Image shown, 200 OK

**Screenshots:**
<img width="439" alt="Screenshot 2023-09-25 at 11 29 21" src="https://github.com/ironforge-cloud/soldev-ui/assets/172594/59789f99-7294-46dd-b672-2a2c7f62daf4">

**Comment by mikemaccana** [comment]
CC @italoacasas @jamesrp13 - thanks for investigating gents!

**Comment by italoacasas** [comment]
This is probably because it's a new asset that we need to copy into https://github.com/ironforge-cloud/soldev-ui/tree/master/public/assets.

@jamesrp13, let me know if you have time for this. If not, I can get someone from my team to do it.
