### ISSUE TITLE
Miss-information about data ordering ...

### ISSUE THREAD

**Issue by pooriagg** [ironforge-cloud/soldev-ui#22]
Hello, dear soldev team. i think there is a mistake in section "Data Order" FROM "Dealing with Accounts" subject, that you say you must always place the dynamic variables like Vectors and strings in the end of the Account's data structure to be able to keep track of static variables like ids very easy BUT it really does not matter how to order them for example: 

![Screenshot 2023-10-03 192401](https://github.com/ironforge-cloud/soldev-ui/assets/104061307/46814bd0-0f3c-4df7-b5f8-af753a65cddc)

#[account]
pub  struct Data {
     scores: Vec<u8>,
     id: u8
}

- In the top example you must specify a static space for your vector, in the account creation time it looks like it is dynamic but in Solana under the hood it is static beacuz the blockchain's space is limited and we have exatcly specify how mush space we want to rent.

Raw data output for Data's PDA account (with considering10 elements in the vector)  :
- <Buffer ce 9c 3b bc 12 4f f0 e8 03 00 00 00 0a 05 ff 00 00 00 00 00 00 00 01>
discriminator(8 bytes) + vector-u8(4 + (10 * 1)) + id-u8(1 byte)

- Memcmp for tracking the "id" section:
{
     offset: 8 + 14,
     bytes: base58.encode(id)
}

**Comment by italoacasas** [comment]
cc @jamesrp13

**Comment by jamesrp13** [comment]
Hey @pooriagg the content isn't hosted or maintained by the Soldev org. We at Unboxed take care of that. Would you mind creating this issue over there at [the course repo](https://github.com/Unboxed-Software/solana-course) and tagging me? Thanks!
