### ISSUE TITLE
[Bug]: Alternate method to import Keypair from @solana/web3.js 

### ISSUE THREAD

**Issue by adlonymous** [ironforge-cloud/soldev-ui#38]
**Describe the bug:**

In the Cryptography lesson (https://www.soldev.app/course/intro-to-cryptography), while using the following method to generate a Keypair in TypeScript using @solana/web3.js:

import { Keypair } from "@solana/web3.js";

I was getting the following error:

Property 'generate' does not exist on type 'typeof import("@solana/web3.js")'

**Addition/Replacement to code to be made**

const { Keypair } = require("@solana/web3.js");

**Comment by italoacasas** [comment]
cc @jamesrp13

**Comment by jamesrp13** [comment]
@adlonymous if you haven't already moved this issue to https://github.com/unboxed-software/solana-course I suggest doing so. I don't check the issues in the Soldev repo for course feedback/issues.
