### ISSUE TITLE
Translate to Urdu / Hindi

### ISSUE THREAD

**Issue by metasal1** [ironforge-cloud/soldev-ui#46]
**Describe the solution you'd like**
Rewrite the course in Urdu or Hindi

**Comment by draghtnight** [comment]
[]()

**Comment by draghtnight** [comment]
> **Describe the solution you'd like**
> 
> Rewrite the course in Urdu or Hindi
> 
>

**Comment by TouchstoneTheDev** [comment]
is this complete can someone close it on GIB

**Comment by iamsatyajit05** [comment]
can you provide exact link to a course?
